const images = document.querySelectorAll("img");

async function isAIGenerated(src) {
    const response = (await fetch(`http://127.0.0.1:5000/inference?src=${src}`));
    const data = await response.json();
    console.log(data)
    return parseFloat(data.artificial) >= 0.5;
}
for (const element of images) {
    const isAI = isAIGenerated(element.src).then(result => result);
    if (isAI) {
        element.src = "";
        images.alt = "This image was generated by AI."
    }
}
