const images = document.querySelectorAll("img");

async function isAIGenerated(src) {
    console.log(src)
    const str = `http://127.0.0.1:5000/inference?src=${src}`;
    const reqSrc = str.split("&").join("%26")
    const response = (await fetch(reqSrc));
    const data = await response.json();
    console.log(data)
    return parseFloat(data.artificial) >= 0.5;
}
for (const element of images) {
    isAIGenerated(element.src).then(res => {
        if (res) {
            element.src = "";
            element.alt = "This image was generated by AI."
        }
    });
}
