let images = document.getElementsByTagName('img');
for(let i = 0; i < images.length; i++) {
    chrome.runtime.sendMessage({msg: 'image', index: i}, function({data, index}){
        images[index].src = data.link;
    });
}

/* const images = document.querySelectorAll("img");
console.log("scriptd loaded")
async function isAIGenerated(src) {
    console.log(src)
    const str = `http://127.0.0.1:5000/inference?src=${src}`;
    const reqSrc = str.split("&").join("%26")
    const response = (await fetch(reqSrc));
    const data = await response.json();
    console.log(data)
    return parseFloat(data.artificial) >= 0.5;
}
function detector(element) {
    console.log("mouseover")
    isAIGenerated(element.src).then(res => {
        if (res) {
            element.src = "";
            element.alt = "This image was generated by AI."
        }
    });
}
for (const element of images) {
    element.addEventListener("mouseover", detector);
}
 */

