import Transformer from "transformer";

const images = document.querySelectorAll("img");

for (const element of images) {
    if (isAIGenerated(element.src)) {
        element.src = "";
        images.alt = "This image was generated by AI."
    }
}

function isAIGenerated(src) {
    
}